/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.ComparisonPoint = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ComparisonPoint model module.
   * @module model/ComparisonPoint
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>ComparisonPoint</code>.
   * @alias module:model/ComparisonPoint
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ComparisonPoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComparisonPoint} obj Optional instance to populate.
   * @return {module:model/ComparisonPoint} The populated <code>ComparisonPoint</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('similar_vehicles_count')) {
        obj['similar_vehicles_count'] = ApiClient.convertToType(data['similar_vehicles_count'], 'Number');
      }
      if (data.hasOwnProperty('dealer_indicator')) {
        obj['dealer_indicator'] = ApiClient.convertToType(data['dealer_indicator'], 'String');
      }
      if (data.hasOwnProperty('vin_price')) {
        obj['vin_price'] = ApiClient.convertToType(data['vin_price'], 'Number');
      }
      if (data.hasOwnProperty('fair_deal_price')) {
        obj['fair_deal_price'] = ApiClient.convertToType(data['fair_deal_price'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Similar Vehicles Count
   * @member {Number} similar_vehicles_count
   */
  exports.prototype['similar_vehicles_count'] = undefined;
  /**
   * Deal Indicator
   * @member {String} dealer_indicator
   */
  exports.prototype['dealer_indicator'] = undefined;
  /**
   * Price for Vin
   * @member {Number} vin_price
   */
  exports.prototype['vin_price'] = undefined;
  /**
   * Fair Deal Price
   * @member {Number} fair_deal_price
   */
  exports.prototype['fair_deal_price'] = undefined;



  return exports;
}));


