/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.Dealer = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Dealer model module.
   * @module model/Dealer
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>Dealer</code>.
   * @alias module:model/Dealer
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>Dealer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Dealer} obj Optional instance to populate.
   * @return {module:model/Dealer} The populated <code>Dealer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('franchise_id')) {
        obj['franchise_id'] = ApiClient.convertToType(data['franchise_id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('zip')) {
        obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('car_type')) {
        obj['car_type'] = ApiClient.convertToType(data['car_type'], 'String');
      }
      if (data.hasOwnProperty('target_url_new')) {
        obj['target_url_new'] = ApiClient.convertToType(data['target_url_new'], 'String');
      }
      if (data.hasOwnProperty('target_url_used')) {
        obj['target_url_used'] = ApiClient.convertToType(data['target_url_used'], 'String');
      }
      if (data.hasOwnProperty('target_url_certified')) {
        obj['target_url_certified'] = ApiClient.convertToType(data['target_url_certified'], 'String');
      }
      if (data.hasOwnProperty('dealer_type')) {
        obj['dealer_type'] = ApiClient.convertToType(data['dealer_type'], 'String');
      }
      if (data.hasOwnProperty('rating')) {
        obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The unique id associated with the dealer in the Marketcheck database
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Dealer franchise id
   * @member {String} franchise_id
   */
  exports.prototype['franchise_id'] = undefined;
  /**
   * Name of the dealer
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Street of the dealer
   * @member {String} street
   */
  exports.prototype['street'] = undefined;
  /**
   * City of the dealer
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * State of the dealer
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Zip of the dealer
   * @member {String} zip
   */
  exports.prototype['zip'] = undefined;
  /**
   * Latutide for the dealer location
   * @member {String} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * Longitude for the dealer location
   * @member {String} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * Contact no of the dealer
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * Car type new|used|certified
   * @member {String} car_type
   */
  exports.prototype['car_type'] = undefined;
  /**
   * Target url for the new cars listing
   * @member {String} target_url_new
   */
  exports.prototype['target_url_new'] = undefined;
  /**
   * Target url for the used cars listing
   * @member {String} target_url_used
   */
  exports.prototype['target_url_used'] = undefined;
  /**
   * Target url for the certified cars listing
   * @member {String} target_url_certified
   */
  exports.prototype['target_url_certified'] = undefined;
  /**
   * Dealer type - independent, franchise, multi-brand, authorized
   * @member {String} dealer_type
   * @default 'independent'
   */
  exports.prototype['dealer_type'] = 'independent';
  /**
   * Overall rating of the dealership on scale 1-5
   * @member {Number} rating
   */
  exports.prototype['rating'] = undefined;



  return exports;
}));


