/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RatingComponents'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RatingComponents'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.DealerRating = factory(root.MarketcheckCarsApi.ApiClient, root.MarketcheckCarsApi.RatingComponents);
  }
}(this, function(ApiClient, RatingComponents) {
  'use strict';




  /**
   * The DealerRating model module.
   * @module model/DealerRating
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>DealerRating</code>.
   * @alias module:model/DealerRating
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>DealerRating</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DealerRating} obj Optional instance to populate.
   * @return {module:model/DealerRating} The populated <code>DealerRating</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('zip')) {
        obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'String');
      }
      if (data.hasOwnProperty('overall_rating')) {
        obj['overall_rating'] = ApiClient.convertToType(data['overall_rating'], 'Number');
      }
      if (data.hasOwnProperty('rating_components')) {
        obj['rating_components'] = ApiClient.convertToType(data['rating_components'], [RatingComponents]);
      }
    }
    return obj;
  }

  /**
   * Name of the dealer
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Street of the dealer
   * @member {String} street
   */
  exports.prototype['street'] = undefined;
  /**
   * City of the dealer
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * State of the dealer
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Zip of the dealer
   * @member {String} zip
   */
  exports.prototype['zip'] = undefined;
  /**
   * Latutide for the dealer location
   * @member {String} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * Longitude for the dealer location
   * @member {String} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * Overall rating of the dealership on scale 1-5
   * @member {Number} overall_rating
   */
  exports.prototype['overall_rating'] = undefined;
  /**
   * @member {Array.<module:model/RatingComponents>} rating_components
   */
  exports.prototype['rating_components'] = undefined;



  return exports;
}));


