/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.DepreciationStats = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DepreciationStats model module.
   * @module model/DepreciationStats
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>DepreciationStats</code>.
   * @alias module:model/DepreciationStats
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>DepreciationStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DepreciationStats} obj Optional instance to populate.
   * @return {module:model/DepreciationStats} The populated <code>DepreciationStats</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('current_value')) {
        obj['current_value'] = ApiClient.convertToType(data['current_value'], 'Number');
      }
      if (data.hasOwnProperty('one_year_from_now')) {
        obj['one_year_from_now'] = ApiClient.convertToType(data['one_year_from_now'], 'Number');
      }
      if (data.hasOwnProperty('one_year_from_now_percent')) {
        obj['one_year_from_now_percent'] = ApiClient.convertToType(data['one_year_from_now_percent'], 'Number');
      }
      if (data.hasOwnProperty('two_year_from_now')) {
        obj['two_year_from_now'] = ApiClient.convertToType(data['two_year_from_now'], 'Number');
      }
      if (data.hasOwnProperty('two_year_from_now_percent')) {
        obj['two_year_from_now_percent'] = ApiClient.convertToType(data['two_year_from_now_percent'], 'Number');
      }
      if (data.hasOwnProperty('five_year_from_now')) {
        obj['five_year_from_now'] = ApiClient.convertToType(data['five_year_from_now'], 'Number');
      }
      if (data.hasOwnProperty('five_year_from_now_percent')) {
        obj['five_year_from_now_percent'] = ApiClient.convertToType(data['five_year_from_now_percent'], 'Number');
      }
    }
    return obj;
  }

  /**
   * ymm_comb_name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Price of year make model combination
   * @member {Number} current_value
   */
  exports.prototype['current_value'] = undefined;
  /**
   * price after one year from now
   * @member {Number} one_year_from_now
   */
  exports.prototype['one_year_from_now'] = undefined;
  /**
   * price depreciation percent after one year from now
   * @member {Number} one_year_from_now_percent
   */
  exports.prototype['one_year_from_now_percent'] = undefined;
  /**
   * price after two year from now
   * @member {Number} two_year_from_now
   */
  exports.prototype['two_year_from_now'] = undefined;
  /**
   * price depreciation percent after two year from now
   * @member {Number} two_year_from_now_percent
   */
  exports.prototype['two_year_from_now_percent'] = undefined;
  /**
   * price after five year from now
   * @member {Number} five_year_from_now
   */
  exports.prototype['five_year_from_now'] = undefined;
  /**
   * price depreciation percent after five year from now
   * @member {Number} five_year_from_now_percent
   */
  exports.prototype['five_year_from_now_percent'] = undefined;



  return exports;
}));


