/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.Economy = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Economy model module.
   * @module model/Economy
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>Economy</code>.
   * @alias module:model/Economy
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Economy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Economy} obj Optional instance to populate.
   * @return {module:model/Economy} The populated <code>Economy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ghg_emissions_rating')) {
        obj['ghg_emissions_rating'] = ApiClient.convertToType(data['ghg_emissions_rating'], 'Number');
      }
      if (data.hasOwnProperty('ghg_emissions_indicator')) {
        obj['ghg_emissions_indicator'] = ApiClient.convertToType(data['ghg_emissions_indicator'], 'String');
      }
      if (data.hasOwnProperty('smog_rating')) {
        obj['smog_rating'] = ApiClient.convertToType(data['smog_rating'], 'Number');
      }
      if (data.hasOwnProperty('smog_indicator')) {
        obj['smog_indicator'] = ApiClient.convertToType(data['smog_indicator'], 'String');
      }
    }
    return obj;
  }

  /**
   * Show vehicle impact on climate change in terms of greeenhouse gases. This rating will be in the range of 1 - 10
   * @member {Number} ghg_emissions_rating
   */
  exports.prototype['ghg_emissions_rating'] = undefined;
  /**
   * Contains text like bad|Good|Very Good| Excellent
   * @member {String} ghg_emissions_indicator
   */
  exports.prototype['ghg_emissions_indicator'] = undefined;
  /**
   * Shows vehicle's emissions of pollutants known to cause smog and other forms of air pollution. This rating will be in the range of 1 - 10
   * @member {Number} smog_rating
   */
  exports.prototype['smog_rating'] = undefined;
  /**
   * Contains text like bad|Good|Very Good| Excellent
   * @member {String} smog_indicator
   */
  exports.prototype['smog_indicator'] = undefined;



  return exports;
}));


