/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.FuelEfficiency = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FuelEfficiency model module.
   * @module model/FuelEfficiency
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>FuelEfficiency</code>.
   * @alias module:model/FuelEfficiency
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>FuelEfficiency</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FuelEfficiency} obj Optional instance to populate.
   * @return {module:model/FuelEfficiency} The populated <code>FuelEfficiency</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('city_mileage')) {
        obj['city_mileage'] = ApiClient.convertToType(data['city_mileage'], 'String');
      }
      if (data.hasOwnProperty('highway_mileage')) {
        obj['highway_mileage'] = ApiClient.convertToType(data['highway_mileage'], 'String');
      }
      if (data.hasOwnProperty('combined_mileage')) {
        obj['combined_mileage'] = ApiClient.convertToType(data['combined_mileage'], 'String');
      }
      if (data.hasOwnProperty('annual_miles')) {
        obj['annual_miles'] = ApiClient.convertToType(data['annual_miles'], 'Number');
      }
      if (data.hasOwnProperty('monthly_fuel_expense')) {
        obj['monthly_fuel_expense'] = ApiClient.convertToType(data['monthly_fuel_expense'], 'Number');
      }
    }
    return obj;
  }

  /**
   * City Mileage in MPG
   * @member {String} city_mileage
   */
  exports.prototype['city_mileage'] = undefined;
  /**
   * Highway Mileage in MPG
   * @member {String} highway_mileage
   */
  exports.prototype['highway_mileage'] = undefined;
  /**
   * Combined Mileage
   * @member {String} combined_mileage
   */
  exports.prototype['combined_mileage'] = undefined;
  /**
   * Annual Miles of Car
   * @member {Number} annual_miles
   */
  exports.prototype['annual_miles'] = undefined;
  /**
   * Monthly fuel expense
   * @member {Number} monthly_fuel_expense
   */
  exports.prototype['monthly_fuel_expense'] = undefined;



  return exports;
}));


