/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.HistoricalListing = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HistoricalListing model module.
   * @module model/HistoricalListing
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>HistoricalListing</code>.
   * Represents a car history entry
   * @alias module:model/HistoricalListing
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>HistoricalListing</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistoricalListing} obj Optional instance to populate.
   * @return {module:model/HistoricalListing} The populated <code>HistoricalListing</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'String');
      }
      if (data.hasOwnProperty('msrp')) {
        obj['msrp'] = ApiClient.convertToType(data['msrp'], 'String');
      }
      if (data.hasOwnProperty('miles')) {
        obj['miles'] = ApiClient.convertToType(data['miles'], 'String');
      }
      if (data.hasOwnProperty('vdp_url')) {
        obj['vdp_url'] = ApiClient.convertToType(data['vdp_url'], 'String');
      }
      if (data.hasOwnProperty('seller_name')) {
        obj['seller_name'] = ApiClient.convertToType(data['seller_name'], 'String');
      }
      if (data.hasOwnProperty('scraped_at')) {
        obj['scraped_at'] = ApiClient.convertToType(data['scraped_at'], 'Number');
      }
      if (data.hasOwnProperty('last_seen_at')) {
        obj['last_seen_at'] = ApiClient.convertToType(data['last_seen_at'], 'Number');
      }
      if (data.hasOwnProperty('source')) {
        obj['source'] = ApiClient.convertToType(data['source'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('zip')) {
        obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique identifier representing a specific listing from the Marketcheck database
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Asking price for the car
   * @member {String} price
   */
  exports.prototype['price'] = undefined;
  /**
   * MSRP for the car
   * @member {String} msrp
   */
  exports.prototype['msrp'] = undefined;
  /**
   * Odometer reading / reported miles usage for the car
   * @member {String} miles
   */
  exports.prototype['miles'] = undefined;
  /**
   * Vehicle Details Page url of the specific car
   * @member {String} vdp_url
   */
  exports.prototype['vdp_url'] = undefined;
  /**
   * Seller name of the listing from the Marketcheck database
   * @member {String} seller_name
   */
  exports.prototype['seller_name'] = undefined;
  /**
   * Listing scraped at timestamp
   * @member {Number} scraped_at
   */
  exports.prototype['scraped_at'] = undefined;
  /**
   * Listing last seen at (most recent) timestamp
   * @member {Number} last_seen_at
   */
  exports.prototype['last_seen_at'] = undefined;
  /**
   * Source website for the listing
   * @member {String} source
   */
  exports.prototype['source'] = undefined;
  /**
   * City of the listing
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * State of the listing
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Zip of the listing
   * @member {String} zip
   */
  exports.prototype['zip'] = undefined;



  return exports;
}));


