/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.PopularityItem = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PopularityItem model module.
   * @module model/PopularityItem
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>PopularityItem</code>.
   * @alias module:model/PopularityItem
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>PopularityItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PopularityItem} obj Optional instance to populate.
   * @return {module:model/PopularityItem} The populated <code>PopularityItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('left')) {
        obj['left'] = ApiClient.convertToType(data['left'], 'Number');
      }
      if (data.hasOwnProperty('right')) {
        obj['right'] = ApiClient.convertToType(data['right'], 'Number');
      }
      if (data.hasOwnProperty('difference')) {
        obj['difference'] = ApiClient.convertToType(data['difference'], 'Number');
      }
      if (data.hasOwnProperty('thumbs')) {
        obj['thumbs'] = ApiClient.convertToType(data['thumbs'], 'String');
      }
      if (data.hasOwnProperty('delta_percent')) {
        obj['delta_percent'] = ApiClient.convertToType(data['delta_percent'], 'Number');
      }
      if (data.hasOwnProperty('color')) {
        obj['color'] = ApiClient.convertToType(data['color'], 'String');
      }
    }
    return obj;
  }

  /**
   * Description for which popularity should be show eg: 2016 ford F-150 Lariat vs All Other Cars
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * Left side rating for above description (2016 ford F-150 Lariat)
   * @member {Number} left
   */
  exports.prototype['left'] = undefined;
  /**
   * Right side rating for above description (All Other Cars)
   * @member {Number} right
   */
  exports.prototype['right'] = undefined;
  /**
   * Difference depending upon left and right analysis
   * @member {Number} difference
   */
  exports.prototype['difference'] = undefined;
  /**
   * Thumbs up/down depending upon left and right analysis numbers
   * @member {String} thumbs
   */
  exports.prototype['thumbs'] = undefined;
  /**
   * Delta percent
   * @member {Number} delta_percent
   */
  exports.prototype['delta_percent'] = undefined;
  /**
   * Color depending upon left and right analysis numbers
   * @member {String} color
   */
  exports.prototype['color'] = undefined;



  return exports;
}));


