/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.ReviewComponents = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ReviewComponents model module.
   * @module model/ReviewComponents
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>ReviewComponents</code>.
   * @alias module:model/ReviewComponents
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ReviewComponents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewComponents} obj Optional instance to populate.
   * @return {module:model/ReviewComponents} The populated <code>ReviewComponents</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('user_name')) {
        obj['user_name'] = ApiClient.convertToType(data['user_name'], 'String');
      }
      if (data.hasOwnProperty('user_rating')) {
        obj['user_rating'] = ApiClient.convertToType(data['user_rating'], 'Number');
      }
      if (data.hasOwnProperty('actual_review')) {
        obj['actual_review'] = ApiClient.convertToType(data['actual_review'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of user who has given review
   * @member {String} user_name
   */
  exports.prototype['user_name'] = undefined;
  /**
   * rating for dealer given by user ranging from 1-5
   * @member {Number} user_rating
   */
  exports.prototype['user_rating'] = undefined;
  /**
   * review of car given by current user
   * @member {String} actual_review
   */
  exports.prototype['actual_review'] = undefined;



  return exports;
}));


