/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.TrendPoint = factory(root.MarketcheckCarsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TrendPoint model module.
   * @module model/TrendPoint
   * @version 1.0.3
   */

  /**
   * Constructs a new <code>TrendPoint</code>.
   * @alias module:model/TrendPoint
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>TrendPoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrendPoint} obj Optional instance to populate.
   * @return {module:model/TrendPoint} The populated <code>TrendPoint</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('miles')) {
        obj['miles'] = ApiClient.convertToType(data['miles'], 'Number');
      }
      if (data.hasOwnProperty('dom')) {
        obj['dom'] = ApiClient.convertToType(data['dom'], 'Number');
      }
      if (data.hasOwnProperty('units')) {
        obj['units'] = ApiClient.convertToType(data['units'], 'Number');
      }
      if (data.hasOwnProperty('msrp')) {
        obj['msrp'] = ApiClient.convertToType(data['msrp'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Price
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * Miles
   * @member {Number} miles
   */
  exports.prototype['miles'] = undefined;
  /**
   * Days on Market
   * @member {Number} dom
   */
  exports.prototype['dom'] = undefined;
  /**
   * Units
   * @member {Number} units
   */
  exports.prototype['units'] = undefined;
  /**
   * MSRP
   * @member {Number} msrp
   */
  exports.prototype['msrp'] = undefined;



  return exports;
}));


