/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/PlotPoint'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/PlotPoint'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.GraphsApi = factory(root.MarketcheckCarsApi.ApiClient, root.MarketcheckCarsApi.Error, root.MarketcheckCarsApi.PlotPoint);
  }
}(this, function(ApiClient, Error, PlotPoint) {
  'use strict';

  /**
   * Graphs service.
   * @module api/GraphsApi
   * @version 1.0.3
   */

  /**
   * Constructs a new GraphsApi. 
   * @alias module:api/GraphsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getPriceMilesPlotData operation.
     * @callback module:api/GraphsApi~getPriceMilesPlotDataCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PlotPoint>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Price, Miles plots data for given criteria
     * [DEPRECIATED Please check this in /search API using plot&#x3D;true]Get price, miles plot data for active cars matching the given VIN&#39;s basic specification or Year, Make, Model, Trim (Optional) criteria
     * @param {String} carType Car type to get the scatter plot data for
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiKey The API Authentication Key. Mandatory with all API calls.
     * @param {String} opts.vin VIN as a reference to the type of car for which plot data is to be returned
     * @param {String} opts.year Year of the car
     * @param {String} opts.make Make of the car
     * @param {String} opts.model Model of the Car
     * @param {String} opts.trim Trim of the Car
     * @param {Number} opts.rows Number of results to return. Default is 1000. Max is 10000
     * @param {module:api/GraphsApi~getPriceMilesPlotDataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PlotPoint>}
     */
    this.getPriceMilesPlotData = function(carType, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'carType' is set
      if (carType === undefined || carType === null) {
        throw new Error("Missing the required parameter 'carType' when calling getPriceMilesPlotData");
      }


      var pathParams = {
      };
      var queryParams = {
        'api_key': opts['apiKey'],
        'vin': opts['vin'],
        'year': opts['year'],
        'make': opts['make'],
        'model': opts['model'],
        'trim': opts['trim'],
        'car_type': carType,
        'rows': opts['rows'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [PlotPoint];

      return this.apiClient.callApi(
        '/plots', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
