/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/HistoricalListing'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/HistoricalListing'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.HistoryApi = factory(root.MarketcheckCarsApi.ApiClient, root.MarketcheckCarsApi.Error, root.MarketcheckCarsApi.HistoricalListing);
  }
}(this, function(ApiClient, Error, HistoricalListing) {
  'use strict';

  /**
   * History service.
   * @module api/HistoryApi
   * @version 1.0.3
   */

  /**
   * Constructs a new HistoryApi. 
   * @alias module:api/HistoryApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the history operation.
     * @callback module:api/HistoryApi~historyCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/HistoricalListing>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a cars online listing history
     * The history API returns online listing history for a car identified by its VIN. History listings are sorted in the descending order of the listing date / last seen date
     * @param {String} vin The VIN to identify the car to fetch the listing history. Must be a valid 17 char VIN
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiKey The API Authentication Key. Mandatory with all API calls.
     * @param {String} opts.fields List of fields to fetch, in case the default fields list in the response is to be trimmed down
     * @param {Number} opts.rows Number of results to return. Default is 10. Max is 50
     * @param {Number} opts.page Page number to fetch the results for the given criteria. Default is 1.
     * @param {module:api/HistoryApi~historyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/HistoricalListing>}
     */
    this.history = function(vin, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'vin' is set
      if (vin === undefined || vin === null) {
        throw new Error("Missing the required parameter 'vin' when calling history");
      }


      var pathParams = {
        'vin': vin
      };
      var queryParams = {
        'api_key': opts['apiKey'],
        'fields': opts['fields'],
        'rows': opts['rows'],
        'page': opts['page'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [HistoricalListing];

      return this.apiClient.callApi(
        '/history/{vin}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
