/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseListing', 'model/Error'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BaseListing'), require('../model/Error'));
  } else {
    // Browser globals (root is window)
    if (!root.MarketcheckCarsApi) {
      root.MarketcheckCarsApi = {};
    }
    root.MarketcheckCarsApi.InventoryApi = factory(root.MarketcheckCarsApi.ApiClient, root.MarketcheckCarsApi.BaseListing, root.MarketcheckCarsApi.Error);
  }
}(this, function(ApiClient, BaseListing, Error) {
  'use strict';

  /**
   * Inventory service.
   * @module api/InventoryApi
   * @version 1.0.3
   */

  /**
   * Constructs a new InventoryApi. 
   * @alias module:api/InventoryApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getDealerActiveInventory operation.
     * @callback module:api/InventoryApi~getDealerActiveInventoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BaseListing} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Dealer inventory
     * Get a dealer&#39;s currently active inventory
     * @param {String} dealerId Id representing the dealer to fetch the active inventory for
     * @param {Object} opts Optional parameters
     * @param {String} opts.apiKey The API Authentication Key. Mandatory with all API calls.
     * @param {Number} opts.rows Number of results to return. Default is 10. Max is 50
     * @param {Number} opts.start Page number to fetch the results for the given criteria. Default is 1. Pagination is allowed only till first 1000 results for the search and sort criteria. The page value can be only between 1 to 1000/rows
     * @param {module:api/InventoryApi~getDealerActiveInventoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BaseListing}
     */
    this.getDealerActiveInventory = function(dealerId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'dealerId' is set
      if (dealerId === undefined || dealerId === null) {
        throw new Error("Missing the required parameter 'dealerId' when calling getDealerActiveInventory");
      }


      var pathParams = {
        'dealer_id': dealerId
      };
      var queryParams = {
        'api_key': opts['apiKey'],
        'rows': opts['rows'],
        'start': opts['start'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = BaseListing;

      return this.apiClient.callApi(
        '/dealer/{dealer_id}/active/inventory', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getDealerHistoricalInventory operation.
     * @callback module:api/InventoryApi~getDealerHistoricalInventoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BaseListing} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Dealer&#39;s historical inventory
     * [v1 : Not Implemented Yet] - Get a dealer&#39;s historical inventory
     * @param {String} dealerId Id representing the dealer to fetch the active inventory for
     * @param {module:api/InventoryApi~getDealerHistoricalInventoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BaseListing}
     */
    this.getDealerHistoricalInventory = function(dealerId, callback) {
      var postBody = null;

      // verify the required parameter 'dealerId' is set
      if (dealerId === undefined || dealerId === null) {
        throw new Error("Missing the required parameter 'dealerId' when calling getDealerHistoricalInventory");
      }


      var pathParams = {
        'dealer_id': dealerId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = BaseListing;

      return this.apiClient.callApi(
        '/dealer/{dealer_id}/historical/inventory', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
