/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketcheckCarsApi);
  }
}(this, function(expect, MarketcheckCarsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MarketcheckCarsApi.BaseListing();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BaseListing', function() {
    it('should create an instance of BaseListing', function() {
      // uncomment below and update the code to test BaseListing
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be.a(MarketcheckCarsApi.BaseListing);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property heading (base name: "heading")', function() {
      // uncomment below and update the code to test the property heading
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property vin (base name: "vin")', function() {
      // uncomment below and update the code to test the property vin
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property stockNo (base name: "stock_no")', function() {
      // uncomment below and update the code to test the property stockNo
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property miles (base name: "miles")', function() {
      // uncomment below and update the code to test the property miles
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property inventoryType (base name: "inventory_type")', function() {
      // uncomment below and update the code to test the property inventoryType
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property lastSeenAt (base name: "last_seen_at")', function() {
      // uncomment below and update the code to test the property lastSeenAt
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property lastSeenAtDate (base name: "last_seen_at_date")', function() {
      // uncomment below and update the code to test the property lastSeenAtDate
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property scrapedAtDate (base name: "scraped_at_date")', function() {
      // uncomment below and update the code to test the property scrapedAtDate
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property firstSeenAt (base name: "first_seen_at")', function() {
      // uncomment below and update the code to test the property firstSeenAt
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property firstSeenAtDate (base name: "first_seen_at_date")', function() {
      // uncomment below and update the code to test the property firstSeenAtDate
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property refPrice (base name: "ref_price")', function() {
      // uncomment below and update the code to test the property refPrice
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property refMiles (base name: "ref_miles")', function() {
      // uncomment below and update the code to test the property refMiles
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property refPriceDt (base name: "ref_price_dt")', function() {
      // uncomment below and update the code to test the property refPriceDt
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property refMilesDt (base name: "ref_miles_dt")', function() {
      // uncomment below and update the code to test the property refMilesDt
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property dom (base name: "dom")', function() {
      // uncomment below and update the code to test the property dom
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property dom180 (base name: "dom_180")', function() {
      // uncomment below and update the code to test the property dom180
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property domActive (base name: "dom_active")', function() {
      // uncomment below and update the code to test the property domActive
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property sellerType (base name: "seller_type")', function() {
      // uncomment below and update the code to test the property sellerType
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property exteriorColor (base name: "exterior_color")', function() {
      // uncomment below and update the code to test the property exteriorColor
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property interiorColor (base name: "interior_color")', function() {
      // uncomment below and update the code to test the property interiorColor
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property vdpUrl (base name: "vdp_url")', function() {
      // uncomment below and update the code to test the property vdpUrl
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property media (base name: "media")', function() {
      // uncomment below and update the code to test the property media
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property build (base name: "build")', function() {
      // uncomment below and update the code to test the property build
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property dealer (base name: "dealer")', function() {
      // uncomment below and update the code to test the property dealer
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property isCertified (base name: "is_certified")', function() {
      // uncomment below and update the code to test the property isCertified
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instance = new MarketcheckCarsApi.BaseListing();
      //expect(instance).to.be();
    });

  });

}));
