/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketcheckCarsApi);
  }
}(this, function(expect, MarketcheckCarsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MarketcheckCarsApi.Build();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Build', function() {
    it('should create an instance of Build', function() {
      // uncomment below and update the code to test Build
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be.a(MarketcheckCarsApi.Build);
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property make (base name: "make")', function() {
      // uncomment below and update the code to test the property make
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property trim (base name: "trim")', function() {
      // uncomment below and update the code to test the property trim
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property bodyType (base name: "body_type")', function() {
      // uncomment below and update the code to test the property bodyType
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property vehicleType (base name: "vehicle_type")', function() {
      // uncomment below and update the code to test the property vehicleType
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property drivetrain (base name: "drivetrain")', function() {
      // uncomment below and update the code to test the property drivetrain
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property fuelType (base name: "fuel_type")', function() {
      // uncomment below and update the code to test the property fuelType
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property madeIn (base name: "made_in")', function() {
      // uncomment below and update the code to test the property madeIn
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property engine (base name: "engine")', function() {
      // uncomment below and update the code to test the property engine
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property engineBlock (base name: "engine_block")', function() {
      // uncomment below and update the code to test the property engineBlock
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property engineSize (base name: "engine_size")', function() {
      // uncomment below and update the code to test the property engineSize
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property engineMeasure (base name: "engine_measure")', function() {
      // uncomment below and update the code to test the property engineMeasure
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property engineAspiration (base name: "engine_aspiration")', function() {
      // uncomment below and update the code to test the property engineAspiration
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property transmission (base name: "transmission")', function() {
      // uncomment below and update the code to test the property transmission
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property doors (base name: "doors")', function() {
      // uncomment below and update the code to test the property doors
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property cylinders (base name: "cylinders")', function() {
      // uncomment below and update the code to test the property cylinders
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property steeringType (base name: "steering_type")', function() {
      // uncomment below and update the code to test the property steeringType
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property antibrakeSys (base name: "antibrake_sys")', function() {
      // uncomment below and update the code to test the property antibrakeSys
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property tankSize (base name: "tank_size")', function() {
      // uncomment below and update the code to test the property tankSize
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property overallHeight (base name: "overall_height")', function() {
      // uncomment below and update the code to test the property overallHeight
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property overallLength (base name: "overall_length")', function() {
      // uncomment below and update the code to test the property overallLength
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property overallWidth (base name: "overall_width")', function() {
      // uncomment below and update the code to test the property overallWidth
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property stdSeating (base name: "std_seating")', function() {
      // uncomment below and update the code to test the property stdSeating
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property highwayMiles (base name: "highway_miles")', function() {
      // uncomment below and update the code to test the property highwayMiles
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

    it('should have the property cityMiles (base name: "city_miles")', function() {
      // uncomment below and update the code to test the property cityMiles
      //var instance = new MarketcheckCarsApi.Build();
      //expect(instance).to.be();
    });

  });

}));
