/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MarketcheckCarsApi);
  }
}(this, function(expect, MarketcheckCarsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MarketcheckCarsApi.FuelEfficiency();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FuelEfficiency', function() {
    it('should create an instance of FuelEfficiency', function() {
      // uncomment below and update the code to test FuelEfficiency
      //var instance = new MarketcheckCarsApi.FuelEfficiency();
      //expect(instance).to.be.a(MarketcheckCarsApi.FuelEfficiency);
    });

    it('should have the property cityMileage (base name: "city_mileage")', function() {
      // uncomment below and update the code to test the property cityMileage
      //var instance = new MarketcheckCarsApi.FuelEfficiency();
      //expect(instance).to.be();
    });

    it('should have the property highwayMileage (base name: "highway_mileage")', function() {
      // uncomment below and update the code to test the property highwayMileage
      //var instance = new MarketcheckCarsApi.FuelEfficiency();
      //expect(instance).to.be();
    });

    it('should have the property combinedMileage (base name: "combined_mileage")', function() {
      // uncomment below and update the code to test the property combinedMileage
      //var instance = new MarketcheckCarsApi.FuelEfficiency();
      //expect(instance).to.be();
    });

    it('should have the property annualMiles (base name: "annual_miles")', function() {
      // uncomment below and update the code to test the property annualMiles
      //var instance = new MarketcheckCarsApi.FuelEfficiency();
      //expect(instance).to.be();
    });

    it('should have the property monthlyFuelExpense (base name: "monthly_fuel_expense")', function() {
      // uncomment below and update the code to test the property monthlyFuelExpense
      //var instance = new MarketcheckCarsApi.FuelEfficiency();
      //expect(instance).to.be();
    });

  });

}));
